---
title: ""
---

```{r load-libraries, include=FALSE}
library(leaflet)
library(highcharter)
library(palmerpenguins)
library(dplyr)
library(DT)
```

## Seneca Hall

```{r map-leaflet, echo=FALSE}
leaflet() |> addTiles() |> setView(-93.65, 42.0285, zoom = 17)
```

## Palmer Penguins

```{r chart-highcharter, echo=FALSE}
data(penguins, package = "palmerpenguins")
hchart(penguins, "scatter", hcaes(x = body_mass_g, y = flipper_length_mm , group = species))
```

## Some Code

```{r code-example, eval=FALSE}
# Define UI for app that draws a histogram ----
ui <- fluidPage(

  # App title ----
  titlePanel("Hello Shiny!"),

  # Sidebar layout with input and output definitions ----
  sidebarLayout(

    # Sidebar panel for inputs ----
    sidebarPanel(

      # Input: Slider for the number of bins ----
      sliderInput(inputId = "bins",
                  label = "Number of bins:",
                  min = 1,
                  max = 50,
                  value = 30)

    ),

    # Main panel for displaying outputs ----
    mainPanel(

      # Output: Histogram ----
      plotOutput(outputId = "distPlot")

    )
  )
)
```

## A table

```{r table-example, echo=FALSE}
DT::datatable(iris[1:10, ])
```


